[package]
name = "warcode"
version = "0.1.0"
authors = ["partisani"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "2.0.4"
pest = "2.7.5"
pest_derive = "2.7.5"
